### ISSUE TITLE
Any way to use libamf to send large images ?

### ISSUE THREAD

**Issue by iongion** [Pyrodash/libamf#1]
I am using this library for a protocol implementation for websocket.
I have very large images to transfer, sometimes, 5mb in size, if I use AMF0, I get:

```
node_modules/libamf/src/amf/AMF0.js:247
throw new Error('Invalid data type: ' + type);
```

I guess because of the **Buffer** type of Node

If I use AMF3, CPU spikes to 233 % and never finishes serialization.

**Comment by Pyrodash** [comment]
Thanks for bringing this to my attention. This is now fixed in libamf version 1.2.0. For convenience, Buffers will now be automatically converted to ByteArrays when being serialized.

Example:
```javascript
const AMF = require('libamf');
const fs  = require('fs');

fs.readFile(__dirname + '/img.jpg', (err, res) => {
    const serialized = AMF.serialize(res, AMF.ENCODING.AMF3);
    const deserialized = AMF.deserialize(serialized, AMF.ENCODING.AMF3);

    fs.writeFile('deserialized.jpg', deserialized.buffer, (err, res) => {
        if(err) {
            console.log(err);
        } else {
            console.log('Saved successfully');
        }
    });
});
```
