### ISSUE TITLE
Creating invalid AMF3 SOL files

### ISSUE THREAD

**Issue by Rosslington** [Pyrodash/libamf#5]
When writing the buffer from a newly made AMF3 Object, the reader from libamf and from minerva (https://mariani.life/projects/minerva/) fail to load the file. 

Error: `internal/buffer.js:72 Uncaught RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 127. Received 128`

If you create a new SOL file with the same data using minerva, you'll see that they are different and libamf is able able to read AMF3 files created by minerva.

**Comment by Pyrodash** [comment]
Hi, this should be fixed in 18a4af64949b51c42002c431ee041cb7fec914ec.
