### ISSUE TITLE
Create an Externalized Object response on the server side

### ISSUE THREAD

**Issue by cy-polo** [Pyrodash/libamf#7]
Hello,

I would like to be able to reply to the customer with a reply containing an `Externalized Object`, but I don't know how to do it.

Can you help me please? I looked in the source code but I don't understand.
Thanks in advance for your answer!

**Comment by Pyrodash** [comment]
Hey there, sorry for the late reply
What I understand is that you have an externalizable and you'd like to be able to parse/serialize it.

First, we define the class
```js
class MyOrder {}
```
Second, we have to register the class to libamf using the same name of the class in Flash
```js
libamf.registerClassAlias('ClassName', MyOrder);
```
Lastly, we have to define `readExternal` and `writeExternal` on the class. They should be identical to their counter-parts on your Flash end
```js
class MyOrder {
    readExternal(AMF3, traits) {
        this.one = AMF3.readDouble();
        this.two = AMF3.readDouble();
    }

    writeExternal(AMF3, traits) {
        AMF3.writeDouble(this.one);
        AMF3.writeDouble(this.two);
    }
}
```

For more information on externalizables, read [Adobe's documentation](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/utils/IExternalizable.html).

Hope this helped

**Comment by cy-polo** [comment]
Thanks for your answer, I'll try it.

Have a nice day!
